<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart clearfix">
        <div class="fieldset clearfix">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">
					<div class="product-qty">
						<label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
						  <div class="control custom-qty">
							<button  type="button" class="reduced items" onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty ) && qty > 1 ) result.value--;return false;">
									<i class="fa fa-minus"></i>
							</button>   
							 <input type="number"
								   name="qty"
								   id="qty"
								   maxlength="12"
								   value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
								   title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
								   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
								   />
								<button  type="button" class="increase items" onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty )) result.value++;return false;">
									<i class="fa fa-plus"></i>
								</button>
							</div> 
					</div>
                </div>
            <?php endif; ?>
            <div class="actions add-to-cart">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart button btn-cart"
                        id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form));

                    return false;
                }
            });
			
			jQuery(document).ready(function() {
				jQuery(".user-account").click(function() {
				  jQuery(".header-top").slideToggle( "slow", function() {
					// Animation complete.
				  });
				});
				jQuery(".header-search").click(function() {
				  jQuery(".block-search").slideToggle( "slow", function() {
					// Animation complete.
				  });
				});
				jQuery(".description-tab h2").click(function() {
				  jQuery(this).toggleClass("active");
				  jQuery(this).next('div').slideToggle( "slow", function() {
				  
					// Animation complete.
				  });
				});
			});
			
			
			
        });
    </script>
<?php endif; ?>