<?php
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: Magiccart<team.magiccart@gmail.com>
 * @@Create Date: 2014-07-18 20:49:45
 * @@Modify Date: 2016-06-02 15:05:42
 * @@Function:
 */
?>
<?php
if(!$this->_sysCfg->general['enabled']) return;
$socialnetwork = $this->getData('socialnetwork');
$socialCfg  = $this->_sysCfg->{$socialnetwork};
$socials    = array('instagram', 'pinterest', 'flickr', 'picasa');
$selector   = $socialnetwork . '-feed';
$username   = isset($socialCfg["username"]) ? $socialCfg["username"] : '';
if(!$username) return;
$limit      = isset($socialCfg["limit"])    ? $socialCfg["limit"] : 10;
?>
<article class="social-feed clearfix <?php echo $selector ?>">
    <section class="section-title">
        <h4><?php echo $socialnetwork ?></h4>
    </section>
</article>

<script type="text/javascript">
    require([
        'jquery',
        'socialstream',
        ], function($){
            (function($) {
                $('.<?php echo $selector?>').socialstream({
                    socialnetwork: '<?php echo $socialnetwork?>',
                    limit: <?php echo $limit ?>,
                    username: '<?php echo $username ?>'
                }) 
            })(jQuery); 
    });
</script>
