<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>

<?php
	$_postCollection = $block->getPostCollection();
    if (!$_postCollection->count()) return;
?>
<?php $selector = 'alo-content-'.rand(0,999999999); ?>
<div class="<?php echo $selector?> widget block block-recent-posts" data-bind="scope: 'recent-posts'">
    <div class="block-title">
        <strong><?php echo __($this->getTitle()) ?></strong>
    </div>
    <div class="block-content <?php echo $this->getSlide() ? 'lazy' : '' ?>"
    <?php foreach ($this->getFrontendCfg() as $opt) :?>
        data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>'
    <?php endforeach;?>     
    >
    	<?php foreach ($_postCollection as $_post) { ?>
            <?php $_postUrl = $_post->getPostUrl(); ?>
            <?php $_postName = $block->escapeHtml($_post->getTitle()) ?>
            <div class="item">
                <div class="post-description clearfix">
                    <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                    <div class="post-ftimg-hld blog-image al-style-2 image-container">
                        <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                            <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                        </a>
                    </div>
                    <?php } ?>
					<div class="blog_short_text clearfix">
						<div class="post-info clear">
						    <h3>
								<a class="post-item-link" href="<?php echo $_post->getPostUrl() ?>">
									<?php echo $_postName ?>
								</a>
							</h3>
							<div class="post-posed-date">
								<span class="label"><?php echo __('Posted:') ?></span>
								<span class="value"><?php echo $block->getPostedOn($_post, 'j, n, Y') //'F d, Y' ?></span>
							</div>
							<div class="post-text-hld clearfix">
								<?php echo $block->getShorContent($_post) ?>
							</div>
							<a class="post-read-more button-shop btn-bg-outline" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
							   <?php echo __('Read more') ?><i class="fa fa-angle-double-right"></i>
							</a>
						</div>
					</div>
                    
                </div>
                
            </div>

        <?php } ?>
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'slick',
        'alothemes',
        ], function($){
            (function($) {
                var blog  = $('.<?php echo $selector ?> .block-content');
                if(blog.length) $('head').append(magicproduct(blog, '.item'));
            })(jQuery); 
    });
</script>
