<style>
   .causas li{
       list-style-type: circle;
       margin-left: 16px;
   }
   .causas{
       margin-bottom:30px;
   }
   .data-table{
       margin-bottom:20px;
   }
</style>
<h2 class="sub-title">Las posibles causas de este rechazo son:</h2>
<ul class="causas">
   <li>Error en el ingreso de los datos de Cr&eacute;dito o Debito (fecha y/o c&oacute;digo de seguridad).</li>
   <li>Su tarjeta de Cr&eacute;dito o Debito no cuenta con el cupo necesario para cancelar la compra.</li>
   <li>Tarjeta a&uacute;n no habilitada en el sistema financiero.</li>
   <li>Transacci&oacute;n cancelada.</li>
</ul>