<?php
if(!$this->getEnabled()) return;
$selector = 'alo-content-'.rand(0,999999999);
$testimonials = $this->getTestimonials();
if(!count($testimonials)) return;
?>
<div class="<?php echo $selector ?>">
   <?php echo $this->getTitle() ? '<h2 class="block-title title">' . '<span>' . $this->getTitle() . '</span>' . '</h2>' : '' ?>
   <p class="text_column"><?php /* @escapeNotVerified */ echo __('Platea hac egestas himenaeos mi non libero lacus mollis, a lacinia dapibus turpis curae neque ut fringilla lacinia'); ?></p>
    <div class="testimonial"
        data-fade='false'
    <?php foreach ($this->getFrontendCfg() as $opt) :?>
        data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>'
    <?php endforeach;?>  
    >
        <?php $i=0; foreach ($testimonials as $testimonial) :?>
			<div class="item">
				<div class="testimonial-inner">
					<div class="testimonial_text">
                        <div class="content sub-text"><?php echo $testimonial->getText(); ?></div>
                        <div class="clearfix">
                            <div class="customer">
                                    <img class="avatar img-responsive" src="<?php echo $this->getImage($testimonial)?>" alt="<?php echo __($testimonial->getName()) ?>" title="<?php echo __($testimonial->getName()) ?>" />
                            </div>
                            <p class="name title-name"><?php echo $testimonial->getName(); ?></p>
                        </div>
					</div>
				</div>
			</div>
        <?php endforeach ?>
    </div>
</div>

<script type="text/javascript">
    require([
        'jquery',
        'slick',
        'alothemes',
        ], function($){
            (function($) {
                var testimonial  = $('.<?php echo $selector ?> .testimonial');
                if(testimonial.length) magicproduct(testimonial, '.item');
            })(jQuery); 
    });
</script>


