<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$_product = $block->getProduct();
$_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product);
$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart clearfix">
    <div class="fieldset clearfix">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
		    <div class="product-qty">
				<label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
				<div class="control custom-qty">
                    <button  type="button" class="reduced items" onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty ) && qty > 1 ) result.value--;return false;">
                            <i class="fa fa-minus"></i>
                    </button>   
				     <input type="number"
						   name="qty"
						   id="qty"
						   maxlength="12"
						   value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
						   title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
						   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
						   />
						<button  type="button" class="increase items" onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty )) result.value++;return false;">
							<i class="fa fa-plus"></i>
						</button>
				</div>
			</div>
        </div>
        <?php endif; ?>
    </div>
    <div class="actions add-to-cart">
        <button type="submit"
                title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                class="action primary tocart button btn-cart"
                id="product-addtocart-button">
            <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
        </button>
        <?php echo $block->getChildHtml('', true) ?>
        <div class="product-social-links">
            <div class="product-addto-links add-to-links" data-role="add-to-links">
                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                    <a href="#"
                        class="action towishlist"
                        data-post='<?php /* @escapeNotVerified */ echo $_wishlistSubmitParams; ?>'
                        data-action="add-to-wishlist"><i class="fa fa-heart icons"></i><span><?php /* @escapeNotVerified */ echo __('Wish List') ?></span></a>
                <?php endif; ?>
                <a href="#" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product);?>'
                    data-role="add-to-links"
                    class="action tocompare"><i class="fa fa-retweet icons"></i><span><?php /* @escapeNotVerified */ echo __('Compare') ?></span></a>
                <?php if ($block->canEmailToFriend()): ?>
                    <a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
                       class="action mailto friend"><i class="fa fa-envelope"></i><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';

        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });

                widget.catalogAddToCart('submitForm', $(form));

                return false;
            }
        });
    });
</script>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWishlistOptions())?>
        }
    }
</script>
