<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_product = $block->getProduct() ?>
<div class="form-share">
	<?php if ($block->canEmailToFriend()): ?>
		<a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
		   class="action mailto friend"><i class="fa fa-envelope-o"></i><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></a>
	<?php endif; ?>
</div>
