<?php
/**
 * Magiccart 
 * @category 	Magiccart 
 * @copyright 	Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license 	http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-01-08 22:57:12
 * @@Modify Date: 2016-07-20 22:12:01
 * @@Function:
 */
 ?>
<?php if($this->getStatus() == 2) return; ?>
<?php $selector = 'alo-content-'.rand(0,999999999); ?>
<div class= "<?php echo $selector?> magicproduct magiccategory autoplay">
	<?php
	$tabs = $this->getTabs();
	$numTabs = count($tabs);
	if($numTabs): ?>
	    <div class="block-title-tabs">
		<ul class="magictabs" data-ajax ='<?php echo $this->getAjaxCfg() ?>'>
		<?php $activated = $this->getTabActivated();
			$limit = $this->getLimit();
			$single = ($numTabs ==1) ? 'single' : '';
			foreach ($tabs as $type => $name):
				$status  = (!$this->getAjax() || $activated ==$type) ? 'loaded' : '';
				$status .= ($type == $activated) ? " activated $single" : '';
				//echo '<li class="item '.$status.'" data-type ="'.$type.'"><span class="cat_circ"></span><span class ="title">'.__($name).'</span></li>';
				echo '<li class="item '.$status.'" data-type ="'.$type.'"><span class ="title">'.__($name).'</span></li>';
			endforeach;
		?>
		</ul>
	    </div>
	<?php endif ?>
	<div class="ajax_loading" style="display:none" data-url="<?php echo $this->getUrl('magicproduct/index/category')?>"></div>
	<div class="content-products" 
	<?php foreach ($this->getFrontendCfg() as $opt) :?>
		data-<?php echo $opt ?>='<?php echo $this->getData($opt) ?>'
	<?php endforeach;?>        
	>
	<?php 
		$timer = $this->getTimer();
		if($timer) echo $this->getContent('category/gridtimer.phtml');	
		else echo $this->getContent('category/grid.phtml');	
	?>
	</div>
	<!-- <?php
	if($numTabs): ?>
	    <div class="block-title-tabs">
		<ul class="magictabs" data-ajax ='<?php echo $this->getAjaxCfg() ?>'>
		<?php $activated = $this->getTabActivated();
			$limit = $this->getLimit();
			$single = ($numTabs ==1) ? 'single' : '';
			foreach ($tabs as $type => $name):
				$status  = (!$this->getAjax() || $activated ==$type) ? 'loaded' : '';
				$status .= ($type == $activated) ? " activated $single" : '';
				//echo '<li class="item '.$status.'" data-type ="'.$type.'"><span class="cat_circ"></span><span class ="title">'.__($name).'</span></li>';
				echo '<li class="item '.$status.'" data-type ="'.$type.'"><span class ="title">'.__($name).'</span></li>';
			endforeach;
		?>
		</ul>
	    </div>
	<?php endif ?> -->
</div>

<script type="text/javascript">
require(['magicproduct']);

require(['jquery'], function($){
 		jQuery( document ).ready(function() {
 			//jQuery('.magictabs').find('.title').css({'display':'none'});
 			resize();
 			jQuery(window).resize(function(){
 				resize();
 			});
 		});
 		function resize(){
 			var wcont=jQuery(window).width()/2;
			var wload=jQuery('.ajax_loading').width()/2;
			var hpini=wcont-wload;
			jQuery('.ajax_loading').css({'margin-left':'0px','left':hpini+"px"});
 		}
	});
	// require([
	// 	'jquery',
	// 	'slick',
	// 	'magicproduct'
	// 	], function($){
	// 		(function($) {
	// 			jQuery(".<?php echo $selector?>").magicproduct({
	// 				selector : ".<?php echo $selector?>", // Selector product grid
	// 			});
	// 		})(jQuery);	
	// });
</script>

