<?php
/**
 * @project: CartMigration
 * @author : LitExtension
 * @url    : http://litextension.com
 * @email  : litextension@gmail.com
 */
?>
<?php /* @var $block \LitExtension\CartMigration\Block\Adminhtml\Index */ ?>
<?php $notice = $block->getNotice();?>
<script type="text/javascript">
    require(['jquery','lecm','validation'],function($){
        $(document).ready(function(){
            $.LeCaMg({
                url: '<?php echo $block->getUrl('lecm/index/import',array('_secure'=>true)); ?>',
                formKey : '<?php echo $block->getFormKey(); ?>',
                fnResume: '<?php echo $notice['fn_resume']; ?>',
                timeDelay: '<?php echo $notice['setting']['delay'] * 1000?>',
                autoRetry: '<?php echo $notice['setting']['retry'] * 1000?>'
            });
        });
    });
</script>
<div class="le-content-migration">
    <div id="w" class="clearfix">
        <div id="sidemenu">
            <div id="menu-setup" class="stepmenu open"><strong> 1. <?php echo __("Source Cart Setup"); ?></strong></div>
            <div id="menu-config"  class="stepmenu"><strong> 2. <?php echo __("Configuration"); ?></strong></div>
            <div id="menu-confirm"  class="stepmenu"><strong> 3. <?php echo __("Migration"); ?></strong></div>
        </div>

        <div id="le-content">
            <?php $recent = $block->isRecent(); ?>
            <?php if($recent && !$notice['is_running']){ ?>
                <div id="lecamg-recent" class="contentblock" style="">
                    <?php echo $block->getChildBlock('lecm.recent')->setRecent($recent)->toHtml();?>
                </div>
            <?php } ?>

            <?php if($notice['is_running']){ ?>
            <div id="lecamg-resume" class="contentblock">
                <?php echo $block->getChildBlock('lecm.resume')->setNotice($notice)->toHtml();?>
            </div>
            <?php } ?>
            <div id="lecamg-setup" class="contentblock">
                <?php echo $block->getChildBlock('lecm.setup')->setNotice($notice)->toHtml();?>
            </div>
            <div id="lecamg-config" class="contentblock" style="display: none;"></div>
            <div id="lecamg-confirm" class="contentblock" style="display: none;"></div>
            <div id="lecamg-import" class="contentblock" style="display: none;"></div>
        </div>

    </div>

    <div class="le-footer-migration">
        <p><?php echo __('Cart Migration by LitExtension ver ');?> <?php echo $block->getVersion(); ?></p>
    </div>
</div>
