<?php
// @codingStandardsIgnoreFile
?>
<?php if($this->isEnabled()) : ?>
    <?php $helper = $this->helper('WeltPixel\GoogleTagManager\Helper\Data'); ?>
    <?php $category = $this->getCurrentCategory(); ?>
    <?php $productCollection = $this->getProductCollection(); ?>
    <?php if (count($productCollection)) : ?>
        <?php $categoryProducts = array(); ?>
        <?php $i = 1; ?>
        <?php foreach($productCollection as $product) : ?>
            <?php $categoryProduct = array(); ?>
            <?php $categoryPath = $helper->getGtmCategory($category); ?>
            <?php $extraData = $helper->getPrice($product); ?>
            <?php $price = $extraData['finalPrice']; ?>
            <?php $color = $extraData['color']; ?>
            <?php $categoryProduct['name'] = html_entity_decode($product->getName()); ?>
            <?php $categoryProduct['id'] = $helper->getGtmProductId($product); ?>
            <?php $categoryProduct['price'] = $price; ?>
            <?php if ($helper->isBrandEnabled()) : ?>
            <?php $categoryProduct['brand'] = $helper->getGtmBrand($product); ?>
            <?php endif;?>
            <?php $categoryProduct['category'] = $categoryPath; ?>
            <?php $categoryProduct['variant'] = $color; ?>
            <?php $categoryProduct['list'] = $categoryPath . '/' . $helper->getCurrentPage(); ?>
            <?php $categoryProduct['position'] = $i; ?>
            <?php $categoryProducts[] = $categoryProduct; ?>
            <?php $i++ ; ?>
        <?php endforeach; ?>
        <?php $this->setEcommerceData('currencyCode', $this->getCurrencyCode()); ?>
        <?php $this->setEcommerceData('impressions', $categoryProducts); ?>
    <?php endif; ?>

    <?php if ($helper->isAdWordsRemarketingEnabled()): ?>
        <?php
            $remarketingData = [];
            $remarketingData['ecomm_pagetype'] = \WeltPixel\GoogleTagManager\Model\Api\Remarketing::ECOMM_PAGETYPE_CATEGORY;
            $remarketingData['ecomm_category'] = $helper->getGtmCategory($category);
        ?>
        <?php $this->setDataLayerOption('google_tag_params', $remarketingData); ?>
    <?php endif; ?>
<?php endif; ?>
