<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$ObjectManager= \Magento\Framework\App\ObjectManager::getInstance();
$context = $ObjectManager->get('Magento\Framework\App\Http\Context');
$isLoggedIn = $context->getValue(\Magento\Customer\Model\Context::CONTEXT_AUTH);
//$msg = $isLoggedIn ? __('Welcome') .', '. $customerSession->getCustomer()->getName() : $this->getWelcome() 
?>
<link href='//fonts.googleapis.com/css?family=Karla:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
<link href="//fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet">
<link href='//fonts.googleapis.com/css?family=Crimson+Text:400,400italic,600,600italic,700,700italic' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Condiment' rel='stylesheet' type='text/css'>
<script>
require(['jquery'], function($){
    jQuery(document).ready(function() {
		jQuery(".user-account").click(function() {
		  jQuery(".header-top").slideToggle( "slow", function() {
			// Animation complete.
		  });
		});
		jQuery(".customer-support a, .shopbtn a").click(function() {
		  jQuery(".header-usp").slideToggle( "slow", function() {
			// Animation complete.
		  });
		});
		jQuery(".header-search").click(function() {
		  jQuery(".block-search").slideToggle( "slow", function() {
			// Animation complete.
		  });
		});
		jQuery(".chat-icon").click(function() {
		 jQuery('#olark-wrapper .olark-launch-button').click()
		});
	});
});
</script>

<header class="page-header alothemes">
    <div class="header">
		<div class="header-info-custom">
    		<div class="container">
				<div class="row">
					<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-info-custom')->toHtml(); ?>
					<div class="col-sm-3 col-lg-3 col-md-3 col-xs-4 col1 toplink">
						<div class="header-setting tool-header shopbtn hide">
							<a title="Carro de Compras" href="javascript:void(0)" class="icon fa fa-comments-o"></a>
						</div>
						<div class="header-setting tool-header">
							<a title="Mi Cuenta" href="javascript:void(0)" target="_blank" class="user-account icon fa fa-user"></a>
						</div>
						<div class="header-setting tool-header">
							<a title="Mi lista de deseos" href="<?php echo $this->getUrl('wishlist') ?>" target="_blank" class="wishlist icon fa fa-heart-o"></a>
						</div>
						<div class="content-cart">
							<?php echo $this->getChildHtml('minicart'); ?>
						</div> 
					</div>
					
				</div>
    		</div>
    	</div>
		<div class="header-usp">
			<div class="container">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shop-phone')->toHtml(); ?> 
			</div>
		</div>
		<div class="header-top">
			<div class="container">
				<div class="top-left">
					<div class="header-top-link">
						<?php echo $this->getChildHtml('header.links'); ?>
					</div>
				</div>
				<div class="top-right">
					<?php echo $this->getChildHtml('currency'); ?>
				    <?php echo $this->getChildHtml('store_language'); ?>
				</div>
			</div>
		</div>
		<div class="header-content">
			<div class="container">
				<div class="row">
					<div class="col-md-4 col-sm-4 col-xs-12"> 
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-socials')->toHtml(); ?>
					</div>
					<div class="content-logo col-md-4 col-sm-4 col-xs-12">
						<div class="header-logo">
							<?php echo $this->getChildHtml('logo'); ?>
						</div>
					</div>
					<div class="col-md-4 col-sm-4 col-xs-12">
						<?php echo $this->getChildHtml('top.search'); ?>
						<div class="header-search hide">
							<i class="fa fa-search"></i>
						</div>
						<?php /* <div class="position-right">
							<div class="header-search">
								<div class="search-switcher">
									<div class="icon-search toggle-tab-search">
										<i class="fa fa-search"></i>
									</div>
									<div class="dropdown-switcher toggle-content">
										<div class="top-search-alo container">
											<?php echo $this->getChildHtml('top.search'); ?>
										</div>
									</div>
								</div>
							</div> 
						</div> */ ?>
					</div>
					<div class="menu-mobile">
						<span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
					</div>
				</div>
			</div>
		</div>
		<div class="header-bottom header-sticker">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<?php echo $this->getChildHtml('navigation.sections'); ?>
						<?php //echo $this->getChildHtml('catalog.topnav'); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
<?php 
	if(!$isLoggedIn){
		?>
		<script>
			require(['jquery'], function($){
				$('.header-top-link .links li')
				if($('.header-top-link .links li').length){
					$('.header-top-link .links li')[0].remove();
				}
			});
			</script>
		<?php
	}
?>